# Generated by Django 4.0.4 on 2022-06-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Azeroth_Broker', '0002_rename_server_vendedor_discord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidade',
            new_name='apellidos',
        ),
    ]
