# Generated by Django 4.0.4 on 2022-06-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Azeroth_Broker', '0003_juego_rename_apellidade_usuario_apellidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderador',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
